services:
  event_sourcing.payment_repository:
    class: Repository\PaymentRepository
    arguments:
      - "@broadway.event_store"
      - "@broadway.event_handling.event_bus"

  event_sourcing.create_payment_handler:
    class: Handler\Payment\CreateHandler
    arguments:
      - "@event_sourcing.payment_repository"
    tags:
      - { name: command_handler }

  event_sourcing.cancel_payment_handler:
    class: Handler\Payment\CancelHandler
    arguments:
      - "@event_sourcing.payment_repository"
    tags:
      - { name: command_handler }

  event_sourcing.capture_payment_handler:
    class: Handler\Payment\CaptureHandler
    arguments:
      - "@event_sourcing.payment_repository"
    tags:
      - { name: command_handler }

  event_sourcing.refund_payment_handler:
    class: Handler\Payment\RefundHandler
    arguments:
      - "@event_sourcing.payment_repository"
    tags:
      - { name: command_handler }
