services:
  event_sourcing.create_payment_command:
    class: ToyProject\EventSourcingBundle\Command\CreatePaymentCommand
    arguments:
      - "@event_sourcing.uuid_generator"
      - "@broadway.command_handling.command_bus"
    tags:
      - { name: console.command }

  event_sourcing.uuid_generator:
    class: Broadway\UuidGenerator\Rfc4122\Version4Generator
